<template>
  <div class="zhc-birt-cell-children">
    <template v-for="child in children">
      <birt-work-book
        v-if="child.controlName=='BirtWorkBook'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <!-- <birt-grid-sheet
        v-if="child.controlName=='BirtGridSheet'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />-->
      <birt-form-sheet
        v-if="child.controlName=='BirtFormSheet'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <el-row
        v-if="child.controlName=='ElRow'"
        :gutter="child.gutter"
        :style="child.style"
        :key="child.controlId"
      >
        <birt-cell-children v-if="child.children" :children="child.children" />
      </el-row>
      <el-col
        v-if="child.controlName=='ElCol'"
        :span="child.span"
        :style="child.style"
        :key="child.controlId"
      >
        <birt-cell-children v-if="child.children" :children="child.children" />
      </el-col>
      <el-card v-if="child.controlName=='ElCard'" :style="child.style" :key="child.controlId">
        <birt-cell-children v-if="child.children" :children="child.children" />
      </el-card>

      <hc-button
        v-if="child.controlName=='HcButton'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
        :scope="scope"
      />
      <hc-radio-group
        v-if="child.controlName=='HcRadioGroup'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-checkbox
        v-if="child.controlName=='HcCheckbox'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-image-title
        v-if="child.controlName=='HcImageTitle'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-text-label
        v-if="child.controlName=='HcTextLabel'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
        :bind-dataset="getParentDataSet(child.dataset)"
      />
      <hc-divider
        v-if="child.controlName=='HcDivider'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-carousel
        v-if="child.controlName=='HcCarousel'"
        :ref="child.controlId"
        :conf="child"
        :key="child.controlId"
      />
      <hc-timeline
        v-if="child.controlName=='HcTimeline'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
        :dataset-datas="getDataSetData(child.dataset)"
      />
      <hc-loop-scroll
        v-if="child.controlName=='HcLoopScroll'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-progress
        v-if="child.controlName=='HcProgress'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-tabs
        v-if="child.controlName=='HcTabs'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-steps
        v-if="child.controlName=='HcSteps'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-video
        v-if="child.controlName=='HcVideo'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-data-list
        v-if="child.controlName=='HcDataList'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
        :dataset-datas="getDataSetData(child.dataset)"
      />
      <hc-table
        v-if="child.controlName=='HcTable'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
        :dataset-datas="getDataSetData(child.dataset)"
      />
      <hc-tree
        v-if="child.controlName=='HcTree'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
        :dataset-datas="getDataSetData(child.dataset)"
      />
      <hc-input-filter
        v-if="child.controlName=='HcInputFilter'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
      <hc-dialog
        v-if="child.controlName=='HcDialog'"
        :ref="child.controlId"
        :key="child.controlId"
        :conf="child"
      />
    </template>
  </div>
</template>


<script>
import cellchildren from "./mixins/cellchildren";

export default {
  name: "BirtCellChildren",
  mixins: [cellchildren]
};
</script>

